# Generated by Django 2.2 on 2020-08-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        ('Client', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_user', to='User.User')),
            ],
            options={
                'verbose_name': 'Invigilator',
                'verbose_name_plural': 'Invigilators',
            },
        ),
        migrations.CreateModel(
            name='InvigilatorOrderAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_order_assignment_invigilator', to='Invigilator.Invigilator')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_order_assignment_order', to='Orders.Order')),
            ],
            options={
                'verbose_name': 'Invigilator Order Assignment',
                'verbose_name_plural': 'Invigilator Order Assignments',
            },
        ),
        migrations.CreateModel(
            name='InvigilatorClientMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('message_from', models.TextField(blank=True, choices=[('Client', 'Client'), ('Invigilator', 'Invigilator')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_client_chat_client', to='Client.Client')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_client_chat_invigilator', to='Invigilator.Invigilator')),
            ],
            options={
                'verbose_name': 'Invigilator Client Message',
                'verbose_name_plural': 'Invigilator Client Message',
            },
        ),
    ]
