# Generated by Django 2.2 on 2020-07-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_mobilenumberotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorOrderAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_order_assignment_invigilator', to='User.User')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_order_assignment_order', to='User.User')),
            ],
            options={
                'verbose_name': 'Invigilator Order Assignment',
                'verbose_name_plural': 'Invigilator Order Assignments',
            },
        ),
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_coordinates', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_user', to='User.User')),
            ],
            options={
                'verbose_name': 'Invigilator',
                'verbose_name_plural': 'Invigilators',
            },
        ),
    ]
