# Generated by Django 2.2 on 2020-07-12 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_clientcart_price'),
        ('Invigilator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilatororderassignment',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_order_assignment_invigilator', to='Invigilator.Invigilator'),
        ),
        migrations.AlterField(
            model_name='invigilatororderassignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_order_assignment_order', to='Orders.Order'),
        ),
        migrations.CreateModel(
            name='InvigilatorClientMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('message_from', models.TextField(blank=True, choices=[('Client', 'Client'), ('Invigilator', 'Invigilator')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_client_chat_client', to='Client.Client')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_client_chat_invigilator', to='Invigilator.Invigilator')),
            ],
            options={
                'verbose_name': 'Invigilator Client Message',
                'verbose_name_plural': 'Invigilator Client Message',
            },
        ),
    ]
