# Generated by Django 2.2 on 2020-09-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_restaurant_mobile'),
        ('Invigilator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Invigilator Restaurant',
                'verbose_name_plural': 'Invigilator Restaurants',
            },
        ),
        migrations.AddField(
            model_name='invigilator',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Restaurant.Restaurant'),
        ),
        migrations.DeleteModel(
            name='InvigilatorOrderAssignment',
        ),
        migrations.AddField(
            model_name='invigilatorrestaurant',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_restaurant_invigilator', to='Invigilator.Invigilator'),
        ),
        migrations.AddField(
            model_name='invigilatorrestaurant',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_invigilator_restaurant_restaurant', to='Restaurant.Restaurant'),
        ),
    ]
