# Generated by Django 2.2 on 2020-09-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invigilator', '0002_auto_20200910_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invigilator',
            name='category',
        ),
    ]
