# Generated by Django 2.2 on 2020-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0007_dishaddons'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcart',
            name='add_ons',
            field=models.ManyToManyField(blank=True, null=True, related_name='client_client_cart_dish_add_ons', to='Dishes.DishAddOns'),
        ),
    ]
