# Generated by Django 2.2 on 2020-10-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_globalpromocode'),
        ('Driver', '0002_auto_20200910_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_restaurant_driver', to='Driver.Driver')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_restaurant_restaurant', to='Restaurant.Restaurant')),
            ],
            options={
                'verbose_name': 'Driver Restaurant',
                'verbose_name_plural': 'Driver Restaurants',
            },
        ),
    ]
