# Generated by Django 2.2 on 2020-09-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_restaurant_mobile'),
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='Restaurant.RestraurantDishesCategory')),
            ],
            options={
                'verbose_name': 'General Dish',
                'verbose_name_plural': 'General Dishes',
            },
        ),
    ]
