# Generated by Django 3.0.5 on 2020-05-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0002_dish_adds_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
