# Generated by Django 3.0.5 on 2020-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0003_dish_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
