# Generated by Django 3.0.5 on 2020-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_auto_20200514_0857'),
        ('Dishes', '0004_auto_20200512_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='categories',
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(to='Restaurant.RestraurantDishesCategory'),
        ),
    ]
