# Generated by Django 2.2 on 2020-05-26 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0006_auto_20200517_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAddOns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_free', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes_dishaddons_dish', to='Dishes.Dish')),
            ],
            options={
                'verbose_name': 'Dish Add On',
                'verbose_name_plural': 'Dish Add Ons',
            },
        ),
    ]
