# Generated by Django 2.2 on 2020-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0007_dishaddons'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishaddons',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
