# Generated by Django 2.2 on 2020-07-11 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantRating',
        ),
    ]
