# Generated by Django 2.2 on 2020-09-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantDriver',
        ),
    ]
