# Generated by Django 3.0.5 on 2020-05-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdriver',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='restaurantdriver',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_restaurant_driver_restaurant', to='Restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantpromocode',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
