# Generated by Django 2.2 on 2020-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_delete_restaurantdriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
