# Generated by Django 3.0.5 on 2020-05-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_auto_20200508_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='unique_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
