# Generated by Django 2.2 on 2020-09-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20200909_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
