# Generated by Django 3.0.5 on 2020-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_auto_20200510_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdriver',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
