# Generated by Django 3.0.5 on 2020-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_auto_20200512_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestraurantDishesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restraurant Dishes Category',
                'verbose_name_plural': 'Restraurant Dishes Categories',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(to='Restaurant.RestraurantDishesCategory'),
        ),
    ]
