# Generated by Django 3.0.5 on 2020-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_auto_20200514_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpromocode',
            name='category',
            field=models.ManyToManyField(to='Restaurant.RestraurantDishesCategory'),
        ),
    ]
