# Generated by Django 3.0.5 on 2020-05-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_restaurantpromocode_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Restaurant.RestraurantDishesCategory'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location_coordinates',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
