# Generated by Django 3.0.5 on 2020-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_auto_20200517_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
