# Generated by Django 2.2 on 2020-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_restaurant_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location_coordinates',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
