# Generated by Django 2.2 on 2020-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_mobilenumberotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
