# Generated by Django 2.2 on 2020-08-19 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dishes', '0001_initial'),
        ('Restaurant', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.TextField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Payment', 'Online Payment')], null=True)),
                ('is_delivered', models.BooleanField(blank=True, default=False, null=True)),
                ('is_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.TextField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('preparing', 'preparing'), ('packaging', 'packaging'), ('on_way', 'on_way'), ('delivered', 'delivered')], null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('client_address_details', models.TextField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_client', to='Client.Client')),
                ('promocode_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_promocode_used', to='Restaurant.RestaurantPromocode')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_restaurant', to='Restaurant.Restaurant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('add_ons', models.ManyToManyField(blank=True, null=True, related_name='orders_order_dish_dish_add_ons', to='Dishes.DishAddOns')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_dish_dish', to='Dishes.Dish')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_dish_order', to='Orders.Order')),
            ],
            options={
                'verbose_name': 'Order Dish',
                'verbose_name_plural': 'Order Dishes',
            },
        ),
        migrations.CreateModel(
            name='OngoingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_ongoing_order_order', to='Orders.Order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_ongoing_order_restaurant', to='Restaurant.Restaurant')),
            ],
            options={
                'verbose_name': 'Ongoing Order',
                'verbose_name_plural': 'Ongoing Orders',
            },
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_incoming_order_order', to='Orders.Order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_incoming_order_restaurant', to='Restaurant.Restaurant')),
            ],
            options={
                'verbose_name': 'Incoming Order',
                'verbose_name_plural': 'Incoming Orders',
            },
        ),
    ]
