# Generated by Django 2.2 on 2020-06-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20200609_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.TextField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Payment', 'Online Payment')], null=True),
        ),
        migrations.CreateModel(
            name='OngoingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_ongoing_order_order', to='Orders.Order')),
            ],
            options={
                'verbose_name': 'Ongoing Order',
                'verbose_name_plural': 'Ongoing Orders',
            },
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_incoming_order_order', to='Orders.Order')),
            ],
            options={
                'verbose_name': 'Incoming Order',
                'verbose_name_plural': 'Incoming Orders',
            },
        ),
    ]
