# Generated by Django 2.2 on 2020-06-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0010_auto_20200518_0549'),
        ('Orders', '0004_auto_20200623_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingorder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_incoming_order_restaurant', to='Restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='ongoingorder',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_ongoing_order_restaurant', to='Restaurant.Restaurant'),
        ),
    ]
