# Generated by Django 2.2 on 2020-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_auto_20200623_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('preparing', 'preparing'), ('packaging', 'packaging'), ('on_way', 'on_way'), ('delivered', 'delivered')], null=True),
        ),
    ]
