# Generated by Django 2.2 on 2020-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0007_dishaddons'),
        ('Orders', '0006_auto_20200625_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdish',
            name='add_ons',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders_order_dish_dish_add_ons', to='Dishes.DishAddOns'),
        ),
    ]
